services:
  mysql:
    image: mysql:8.0
    container_name: newjeans-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  redis:
    image: "redis:alpine"
    container_name: newjeans-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  app:
    image: swp0927/newjeans-server-local:latest
    container_name: newjeans-spring-app
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  frontend:
    image: tjmedia12/news_app:v18

    ports:
      - "5173:80"

volumes:
  mysql_data:
  redis_data:
